### ISSUE TITLE
大佬，项目跑不起来！

### ISSUE THREAD

**Issue by zombiu** [zhangyong5566/TGVideoConver#1]
我的as是3.5，ndk版本是20.1.5948944
···
Calling mockable JAR artifact transform to create file: C:\Users\pc\.gradle\caches\transforms-2\files-2.1\bfbd7f92a4f6fed1b1361a5cbc6a8e8d\android.jar with input D:\Android\Sdk\platforms\android-28\android.jar
process_begin: CreateProcess(NULL, "", ...) failed.
D:/Android/Sdk/ndk/20.1.5948944/build//../build/core/add-application.mk:178: *** Android NDK: APP_STL gnustl_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
executing external native build for ndkBuild G:\project\proj\tg\TGVideoConver-master\app\src\main\jni\Android.mk

FAILURE: Build failed with an exception.

* What went wrong:
executing external native build for ndkBuild G:\project\proj\tg\TGVideoConver-master\app\src\main\jni\Android.mk
···

**Comment by zhangyong5566** [comment]
@zombiu 不要用那么高的版本，我ndk用的是r16b

**Comment by zombiu** [comment]
谢谢大佬，我把gradle版本升到3.5.0就好了！

**Comment by zombiu** [comment]
还有注释了这个
#NDK_TOOLCHAIN_VERSION := 4.9
